export const actionTypes = {
  SET_CART: "SET_CART",
  REMOVE_ORDER: "REMOVE_ORDER",
  DEFFER_ORDER: "DEFFER_ORDER",
  DROPDOWN_CHANGE: "DROPDOWN_CHANGE",
  COUNT_ORDERS: "COUNT_ORDERS",
  TOGGLE_EDIT_MODE: "TOGGLE_EDIT_MODE",
};
